extends Node

const PLAYER_NODE_NAME = "main_player"
const BASIC_PLAYER_BULLET_DAMAGE = 2
const BASIC_PLAYER_CHILD_BULLET_DAMAGE = 1
const BASIC_PLAYER_BULLET_SPEED = 1500
const BASIC_PLAYER_MISSILE_DAMAGE = 5
